---
openapi: 3.1.1
info:
  title: ASTM UAM PSU RIS API
  description: |-
    Interface definitions for communication between a UAS Service Supplier (USS) and a 
    Resource Information Service (RIS). This includes APIs for resource definition, resource 
    capacity, and resource status. 
  version: 0.0.0
servers: 
- url: /
security:
- Authority:
  - utm.resource_management
- Authority:
  - utm.resource_processing
- Authority:
  - utm.availability_arbitration
tags:
- name: Resource references
  description: Endpoints exposed by the RIS for details regarding resource references. 
- name: Resource capacities
  description: Endpoints exposed by the RIS for details regarding future resource capacities.
- name: Resource definition
  description: Endpoints exposed by the RIS for details regarding the physical definition and default capacity of a resource. 
- name: Resource status
  description: Endpoints exposed by the RIS for details regarding the current status and capacity of a resource. 
- name: Reports
  description: Endpoints exposed by the PSUs for reporting peer PSU issues.

paths:
  /ris/v1/resource_details/{entityid}:
    summary: Query detailed information of a resource from RIS. 
    get:
      tags:
      - Resource references
      - Resource capacities
      - Resource definition
      - Resource status
      summary: Retrieve the specified resource details from an RIS.
      description: |-
        The RIS hosting this endpoint returns the details (and reference) of an
        resource it manages.
      operationId: getResourceDetailsChanged
      parameters:
      - name: entityid
        in: path
        description: EntityID for this resource.
        required: true
        style: simple
        explode: false
        schema:
          $ref: '../shared-components/schemas.yaml#/components/schemas/EntityID'
      responses:
        "200":
          description: Operational intent details were retrieved successfully.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/QueryResourceDetailsResponse'
        "400":
          description: One or more input parameters were missing or invalid.
          content:
            application/json:
              schema:
                $ref: '../shared-components/schemas.yaml#/components/schemas/ErrorResponse'
        "401":
          description: "Bearer access token was not provided in Authorization header, token could not be decoded, or token was invalid."
          content:
            application/json:
              schema:
                $ref: '../shared-components/schemas.yaml#/components/schemas/ErrorResponse'
        "403":
          description: The access token was decoded successfully but did not include a scope appropriate to this endpoint.
          content:
            application/json:
              schema:
                $ref: '../shared-components/schemas.yaml#/components/schemas/ErrorResponse'
        "404":
          description: The requested Entity could not be found.
          content:
            application/json:
              schema:
                $ref: '../shared-components/schemas.yaml#/components/schemas/ErrorResponse'
        "429":
          description: The client issued too many requests in a short period of time.
          content:
            application/json:
              schema:
                $ref: '../shared-components/schemas.yaml#/components/schemas/ErrorResponse'
      security:
      - Authority:
        - utm.resource_processing
      - Authority:
        - utm.resource_management
  /ris/v1/resource_details/{entityid}/capacities:
    summary: Get future capacity details for the resource. 
    get:
      tags:
      - Resource capacities
      summary: Retrieve the specified resource capacity information from the RIS.
      operationId: getFutureResourceCapacities
      parameters:
      - name: entityid
        in: path
        description: EntityID of the resource.
        required: true
        style: simple
        explode: false
        schema:
          $ref: '../shared-components/schemas.yaml#/components/schemas/EntityID'
      - name: begin_query_time
        in: query
        description: |-
          The time to begin the capacity query. If not provided, endpoint should assume NOW. 
        required: false
        explode: false
        schema:
          $ref: '../shared-components/schemas.yaml#/components/schemas/Time'
      - name: end_query_time
        in: query
        description: |-
          The time to end the capacity query. If not provided, all future
          capacities should be returned. 
        required: false
        explode: false
        schema:
          $ref: '../shared-components/schemas.yaml#/components/schemas/Time'
      responses:
        "200":
          description: List of future capacity details was retrieved successfully. 
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/QueryFutureCapacitiesResponse'
        "400":
          description: One or more input parameters were missing or invalid.
          content:
            application/json:
              schema:
                $ref: '../shared-components/schemas.yaml#/components/schemas/ErrorResponse'
        "401":
          description: "Bearer access token was not provided in Authorization header, token could not be decoded, or token was invalid."
          content:
            application/json:
              schema:
                $ref: '../shared-components/schemas.yaml#/components/schemas/ErrorResponse'
        "403":
          description: The access token was decoded successfully but did not include a scope appropriate to this endpoint.
          content:
            application/json:
              schema:
                $ref: '../shared-components/schemas.yaml#/components/schemas/ErrorResponse'
        "404":
          description: The requested Entity could not be found.
          content:
            application/json:
              schema:
                $ref: '../shared-components/schemas.yaml#/components/schemas/ErrorResponse'
        "429":
          description: The client issued too many requests in a short period of time.
          content:
            application/json:
              schema:
                $ref: '../shared-components/schemas.yaml#/components/schemas/ErrorResponse'
      security:
      - Authority:
        - utm.resource_management
      - Authority:
        - utm.resource_processing
  /ris/v1/resource_details/{entityid}/status:
    summary: Get the current resource status 
    get:
      tags:
      - Resource status
      summary: Retrieve the current resource status from the RIS.
      operationId: getCurrentResourceStatus
      parameters:
      - name: entityid
        in: path
        description: EntityID of the resource.
        required: true
        style: simple
        explode: false
        schema:
          $ref: '../shared-components/schemas.yaml#/components/schemas/EntityID'
      responses:
        "200":
          description: The current status of the resource. 
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/QueryCurrentResourceStatusResponse'
        "400":
          description: One or more input parameters were missing or invalid.
          content:
            application/json:
              schema:
                $ref: '../shared-components/schemas.yaml#/components/schemas/ErrorResponse'
        "401":
          description: "Bearer access token was not provided in Authorization header, token could not be decoded, or token was invalid."
          content:
            application/json:
              schema:
                $ref: '../shared-components/schemas.yaml#/components/schemas/ErrorResponse'
        "403":
          description: The access token was decoded successfully but did not include a scope appropriate to this endpoint.
          content:
            application/json:
              schema:
                $ref: '../shared-components/schemas.yaml#/components/schemas/ErrorResponse'
        "404":
          description: The requested Entity could not be found.
          content:
            application/json:
              schema:
                $ref: '../shared-components/schemas.yaml#/components/schemas/ErrorResponse'
        "429":
          description: The client issued too many requests in a short period of time.
          content:
            application/json:
              schema:
                $ref: '../shared-components/schemas.yaml#/components/schemas/ErrorResponse'
      security:
      - Authority:
        - utm.resource_processing
      - Authority:
        - utm.resource_management
  /ris/v1/resource_details/{entityid}/definition:
    summary: Get the resource definition 
    get:
      tags:
      - Resource definition
      summary: Retrieve the resource definition from the RIS.
      operationId: getResourceDefinition
      parameters:
      - name: entityid
        in: path
        description: EntityID of the resource.
        required: true
        style: simple
        explode: false
        schema:
          $ref: '../shared-components/schemas.yaml#/components/schemas/EntityID'
      responses:
        "200":
          description: The definition of the resource
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/QueryResourceDefinitionResponse'
        "400":
          description: One or more input parameters were missing or invalid.
          content:
            application/json:
              schema:
                $ref: '../shared-components/schemas.yaml#/components/schemas/ErrorResponse'
        "401":
          description: "Bearer access token was not provided in Authorization header, token could not be decoded, or token was invalid."
          content:
            application/json:
              schema:
                $ref: '../shared-components/schemas.yaml#/components/schemas/ErrorResponse'
        "403":
          description: The access token was decoded successfully but did not include a scope appropriate to this endpoint.
          content:
            application/json:
              schema:
                $ref: '../shared-components/schemas.yaml#/components/schemas/ErrorResponse'
        "404":
          description: The requested Entity could not be found.
          content:
            application/json:
              schema:
                $ref: '../shared-components/schemas.yaml#/components/schemas/ErrorResponse'
        "429":
          description: The client issued too many requests in a short period of time.
          content:
            application/json:
              schema:
                $ref: '../shared-components/schemas.yaml#/components/schemas/ErrorResponse'
      security:
      - Authority:
        - utm.resource_processing
      - Authority:
        - utm.resource_management

  /ris/v1/reports:
    $ref: '../shared-components/pathitems.yaml#/components/pathItems/path_ErrorReports'

components:
  securitySchemes:
    Authority:
      $ref: '../shared-components/security.yaml#/components/securitySchemes/Authority'

  schemas:
    QueryResourceDetailsResponse:
      required:
      - resource
      type: object
      properties:
        resource:
          $ref: '../shared-components/schemas.yaml#/components/schemas/Resource'
      description: Response to peer request for the details of resource with the given ID.
    QueryResourceDefinitionResponse:
      required:
      - definition
      type: object
      properties:
        definition:
          $ref: '../shared-components/schemas.yaml#/components/schemas/ResourceDefinition'
      description: Response to peer request for the resource definition of the resource with the given ID.
    QueryCurrentResourceStatusResponse:
      description: Returns the current status of the resource. 
      type: object
      required:
        - current_resource_status
      properties:
        current_resource_status:
          $ref: "../shared-components/schemas.yaml#/components/schemas/CurrentResourceStatus"
    QueryFutureCapacitiesResponse:
      description: Return a list temporary capacities for the future. 
      type: object
      required: 
        - future_capacities
      properties:
        future_capacities:
          description: |-
            An array of future resource capacities, excluding the current active capacity and its end/transition back to the default capacity.
            The current active capacity and its end/transition back to the default capacity is defined by the CurrentResourceStatus ActiveResourceCapacity.
          type: array
          items: 
            $ref: '../shared-components/schemas.yaml#/components/schemas/TemporaryResourceCapacity'
          default: []
