@startuml
participant "Resource operator" as RO
==Set up resources==
RO -> RCIS: POST /RCIS/v1/resource-reference/
RO -> RCIS: PUT /RCIS/v1/resource-reference/{resource-id}/capacities/
RO -> RSIS: POST /RSIS/v1/resource-reference/
RO -> RSIS: PUT /RSIS/v1/resource-reference/{resource-id}/statuses/
==Make resources discoverable==
RO -> DSS: POST /DSS/v1/resource-reference/
note over RO
includes RO, RSIS and RCIS URLs
end note
==DCB discover resources==
DCB -> DSS: POST /DSS/v1/subscriptions/resource-subscription/
DCB <-- DSS: resource operators
DCB -> RO: GET /ResourceOperator/v1/resource-details/{resource-id}
DCB <-- RO: resource details
==DCB get statuses==
DCB -> RSIS: GET /RSIS/v1/resource-reference/{resource-id}/statuses/
DCB <-- RSIS: resource statuses
==DCB get capacities==
DCB -> RCIS: GET /RCIS/v1/resource-reference/{resource-id}/capacities/
DCB <-- RCIS: resource capacities
@enduml