@startuml

title ASTM UAM PSU Interoperability Standard Sequence: Airborne

participant "Resource\noperator" as RO
participant "Vehicle\noperator" as op
participant "Resource Information\nService (RIS)" as RIS
participant "Discovery & Synchronization\nService (DSS)" as DSS
participant "Demand Capacity\nBalancing (DCB)" as DCB
participant "DCB2" as DCB2
participant "Operational Intent\nManagement (OIM)" as OIM
participant "Conformance\nMonitoring (CM)" as CM
participant "CM2" as CM2

op -> op: Operation takes off
==Conformance Monitoring==
op -> CM: Info for CM
CM -> CM: Conformance monitoring
alt If operation in conformance
    note over CM: Do nothing
else If operation not in conformance
    CM -> OIM: PUT /oim/v1/conformance_alert/{entityId}/\n(Nonconforming)
    OIM -> OIM: Define off-nominal volumes
    OIM -> DSS: PUT /dss/v1/operation_intent_references/{entityId}/{ovn}\n(state = Nonconforming; extent = Off-nominal volumes)
    OIM <-- DSS: operation intent reference with subscribers
    loop For all subscribers
        OIM -> DCB2: POST /dcb/v1/operational_intents
        OIM -> DCB: POST /dcb/v1/operational_intents
        DCB2 -> DCB2: Adjust demand values
        DCB -> DCB: Adjust demand values
    end
    OIM -> op: Op nonconformant
    alt If operator can return to conformance
        op -> CM: Tracking info for CM conformant
        CM -> CM: Conformance monitoring
        CM -> OIM: PUT /oim/v1/conformance_alert/{entityId}/\n(Reconforming)
        OIM -> DSS: PUT /dss/v1/operation_intent_references/{entityId}/{ovn}\n(state = Activated)
        OIM <-- DSS: operation intent reference with subscribers
        loop For all subscribers
            OIM -> DCB2: POST /dcb/v1/operational_intents
            OIM -> DCB: POST /dcb/v1/operational_intents
            DCB2 -> DCB2: Adjust demand values
            DCB -> DCB: Adjust demand values
        end
        OIM -> op: Op re-activated
    else If operator can replan intent
        op -> op: Replan intent
        op -> OIM: Updated op request
        note over OIM: OIM does a DCB check
        OIM -> DCB: POST /dcb/v1/imbalance/intent
        OIM <-- DCB: Yes/no, OVNs for all resources, available time ranges
        alt If imbalance detected
            note over OIM: Do not update the operation
            OIM -> op: Op cannot re-activate
            note over op: Operator must replan again in order to re-activate
        else If no imbalance detected
            OIM -> DSS: PUT /dss/v1/operation_intent_references/{entityId}/{ovn}\n(state = Activated)
            DSS -> DSS: Confirms OVNs are correct
            OIM <-- DSS: operation intent reference with subscribers
            loop For all subscribers
                OIM -> DCB2: POST /dcb/v1/operational_intents
                OIM -> DCB: POST /dcb/v1/operational_intents
                DCB2 -> DCB2: Adjust demand values
                DCB -> DCB: Adjust demand values
            end
            OIM -> op: Op re-activated
        end 
    else If op cannot become conformant in time limit
        OIM -> OIM: Define off-nominal volumes
        OIM -> DSS: PUT /dss/v1/operation_intent_references/{entityId}/{ovn}\n(state = Contingent; extent = Off-nominal volumes)
        OIM <-- DSS: operation intent reference with subscribers
        loop For all subscribers
            OIM -> DCB2: POST /dcb/v1/operational_intents
            OIM -> DCB: POST /dcb/v1/operational_intents
            DCB2 -> DCB2: Adjust demand values
            DCB -> DCB: Adjust demand values
        end
        OIM -> op: Op Contingent
        note over OIM: If reason for contingency resolved and \nmeets requirements may transition \nstate back to Activated/DCB-Noncompliant
    end
end

==Conformance monitoring when resource capacity/status/definition changes==
RO -> RIS: Update a future resource capacity/status/definition
alt If capacity change
    RIS -> DSS: PUT /dss/v1/resource_references/{entityid}/{ovn} (updateType=CAPACITY)
else If status change
    RIS -> DSS: PUT /dss/v1/resource_references/{entityid}/{ovn} (updateType=STATUS)
else If definition change
    RIS -> DSS: PUT /dss/v1/resource_references/{entityid}/{ovn} (updateType=DEFINITION)
end
RIS <-- DSS: subscribers, resource-reference including updated ovn
loop For each resource subscriber
    RIS -> DCB: PUT /dcb/v1/resource_details/{entityid}\n(includes resource reference, definition, capacity and status)
    DCB -> DCB: Adjust capacity/status/definition values
    alt If resource definition change
        loop For each operation impacted
            DCB -> OIM: POST /oim/v1/extent_update
        end
    end
    alt If imbalance detected
        alt If extent not already updated for this operation
            DCB -> OIM: POST /oim/v1/imbalance
        end
        loop For each impacted operation
            OIM -> DSS: PUT /dss/v1/operation_intent_references/{entityId}/{ovn}\n(state = DCB-Noncompliant)
            OIM <-- DSS: operation intent reference with subscribers
            loop For all subscribers
                OIM -> DCB2: POST /dcb/v1/operational_intents
                OIM -> DCB: POST /dcb/v1/operational_intents
                DCB2 -> DCB2: Adjust demand values
                DCB -> DCB: Adjust demand values
            end
        end
        alt If operator can replan intent to be DCB-compliant
            op -> op: Replan intent
            op -> OIM: Updated op request
            note over OIM: OIM does a DCB check
            OIM -> DCB: POST /dcb/v1/imbalance/intent
            OIM <-- DCB: Yes/no, OVNs for all resources, available time ranges

            alt If imbalance detected
                note over OIM: Do not update the operation
                OIM -> op: Op cannot activate
                note over op: Operator must replan again in order to activate
            else If no imbalance detected
                OIM -> DSS: PUT /dss/v1/operation_intent_references/{entityId}/{ovn}\n(state = Activated)
                DSS -> DSS: Confirms OVNs are correct
                OIM <-- DSS: operation intent reference with subscribers
                loop For all subscribers
                    OIM -> DCB2: POST /dcb/v1/operational_intents
                    OIM -> DCB: POST /dcb/v1/operational_intents
                    DCB2 -> DCB2: Adjust demand values
                    DCB -> DCB: Adjust demand values
                end
                OIM -> op: Op activated
            end 
        else If op cannot replan intent to be DCB-compliant
            note over op: do nothing\nOperation remains DCB-Noncompliant
    else If no imbalance detected
        note over DCB: do nothing
    end
    RIS -> DCB2: PUT /dcb/v1/resource_details/{entityid}\n(includes resource reference, definition, capacity and status)
    DCB2 -> DCB2: Adjust capacity values
    RIS -> CM: PUT /cm/v1/resource_details/{entityid}\n(includes resource reference, definition, capacity and status)
end

==Position Sharing==
loop 
    CM2 -> CM: GET /cm/v1/operational_intents/{entityid}/telemetry
    CM2 <-- CM: Tracking info for CM
end
@enduml