openapi: 3.1.1
info:
  title: ASTM UAM PSU OIM API
  description: "Interface definitions for the Operational Intent Management function within the Providers of Services to UAM (PSU)\ninteroperability network. Functionality includes sharing details of flight operational intents.\n "
  version: 0.0.0
servers:
- url: /
security:
- Authority:
  - utm.strategic_coordination
- Authority:
  - utm.conformance_monitoring_sa
- Authority:
  - utm.resource_management
- Authority:
  - utm.resource_processing
- Authority:
  - utm.availability_arbitration
 
tags:
- name: Operational intent details
  description: Endpoints exposed by PSU OIMs for interaction with details of operational intents.
- name: Telemetry
- name: Reports
  description: Endpoints exposed by the PSUs for reporting peer PSU issues.
- name: Availability
  description: Endpoints exposed by the DSS for declaring USS availability.
- name: p2p_uam
  description: Endpoints exposed by PSUs for peer-peer communication.
paths:
  /oim/v1/operational_intents/{entityid}:
    summary: Query detailed information of an operational intent from a PSU.
    get:
      tags:
      - Operational intent details
      - p2p_uam
      summary: Retrieve the specified operational intent details from a PSU.
      description: |-
        The PSU hosting this endpoint returns the details (and reference) of an
        operational intent it manages.  While the PSU has a pending request to change the
        operational intent in the DSS, the PSU should report the most recent version the
        PSU knows was accepted by the DSS.  So, before a PSU receives a response
        to create an operational intent reference in the DSS, it should return 404 if
        queried for that operational intent at this endpoint.
      operationId: getOperationalIntentDetails
      parameters:
      - name: entityid
        in: path
        description: EntityID for this operational intent.
        required: true
        style: simple
        explode: false
        schema:
          $ref: '../shared-components/schemas.yaml#/components/schemas/EntityID'
      responses:
        "200":
          description: Operational intent details were retrieved successfully.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetOperationalIntentDetailsResponse'
        "400":
          description: One or more input parameters were missing or invalid.
          content:
            application/json:
              schema:
                $ref: '../shared-components/schemas.yaml#/components/schemas/ErrorResponse'
        "401":
          description: "Bearer access token was not provided in Authorization header, token could not be decoded, or token was invalid."
          content:
            application/json:
              schema:
                $ref: '../shared-components/schemas.yaml#/components/schemas/ErrorResponse'
        "403":
          description: The access token was decoded successfully but did not include a scope appropriate to this endpoint.
          content:
            application/json:
              schema:
                $ref: '../shared-components/schemas.yaml#/components/schemas/ErrorResponse'
        "404":
          description: The requested Entity could not be found.
          content:
            application/json:
              schema:
                $ref: '../shared-components/schemas.yaml#/components/schemas/ErrorResponse'
        "429":
          description: The client issued too many requests in a short period of time.
          content:
            application/json:
              schema:
                $ref: '../shared-components/schemas.yaml#/components/schemas/ErrorResponse'
      security:
      - Authority:
        - utm.strategic_coordination
      - Authority:
        - utm.resource_management
  /oim/v1/conformance_alert/{entityid}:
    summary: |-
      endpoint hosted by OIM to allow CM to provide conformance monitoring alerts including for
      when an operation is detected to be taking off, when it is detected to be non conformant
      and when it is detected to be conformant after a nonconformance. This will usually required
      a change of state for teh operation by the OIM in the DSS
    put:
      tags:
      - Telemetry
      - p2p_uam
      summary: Alert a peer PSU by conformance monitoring.
      description: Notify a peer PSU directly with a conformance monitoring alert (usually requiring a change of state by the OIM in the DSS).
      operationId: notifyConformanceAlert
      parameters:
      - name: entityid
        in: path
        description: EntityID for the impacted operation.
        required: true
        style: simple
        explode: false
        schema:
          $ref: '../shared-components/schemas.yaml#/components/schemas/EntityID'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PutConformanceAlert'
        required: true
      responses:
        "204":
          description: New or updated full resource information received successfully.
        "400":
          description: |-
            * One or more parameters were missing or invalid.
            * The Entity could not be parsed, or contains illegal data.
          content:
            application/json:
              schema:
                $ref: '../shared-components/schemas.yaml#/components/schemas/ErrorResponse'
        "401":
          description: "Bearer access token was not provided in Authorization header, token could not be decoded, or token was invalid."
          content:
            application/json:
              schema:
                $ref: '../shared-components/schemas.yaml#/components/schemas/ErrorResponse'
        "403":
          description: |-
            * The access token was decoded successfully but did not include a scope appropriate to this endpoint.
            * The client identified in the access token is not the manager of this Entity according to the receiving client's records.
          content:
            application/json:
              schema:
                $ref: '../shared-components/schemas.yaml#/components/schemas/ErrorResponse'
        "409":
          description: |-
            The Entity version specified in this message is lower than
            a previously-received notification, or identical to a previously-received
            notification and the Entity is different.
          content:
            application/json:
              schema:
                $ref: '../shared-components/schemas.yaml#/components/schemas/ErrorResponse'
        "429":
          description: The client issued too many requests in a short period of time.
          content:
            application/json:
              schema:
                $ref: '../shared-components/schemas.yaml#/components/schemas/ErrorResponse'
      security:
      - Authority:
        - utm.conformance_monitoring_sa

  /oim/v1/reports:
    summary: Error reports of issues communicating with a peer PSU.
    post:
      $ref: '../shared-components/pathitems.yaml#/components/pathItems/path_ErrorReport/post'

  /oim/v1/uss_availability:
    summary: Share USS availability with users of the airspace. 
    post:
      tags:
      - Availability
      - p2p_uam
      summary: Notify a peer of USS availability change.
      description: Notify a peer of USS availability change which has been reported by 
        a source with utm.availability_arbitration scope. 
      operationId: notifyAvailabilityArbitrationChange
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PutUssAvailabilityDetails'
        required: true
      responses:
        "204":
          description: New or updated full operational intent information received successfully.
        "400":
          description: |-
            * One or more parameters were missing or invalid.
            * The Entity could not be parsed, or contains illegal data.
          content:
            application/json:
              schema:
                $ref: '../shared-components/schemas.yaml#/components/schemas/ErrorResponse'
        "401":
          description: "Bearer access token was not provided in Authorization header, token could not be decoded, or token was invalid."
          content:
            application/json:
              schema:
                $ref: '../shared-components/schemas.yaml#/components/schemas/ErrorResponse'
        "403":
          description: |-
            * The access token was decoded successfully but did not include a scope appropriate to this endpoint.
            * The client identified in the access token is not the manager of this Entity according to the receiving client's records.
          content:
            application/json:
              schema:
                $ref: '../shared-components/schemas.yaml#/components/schemas/ErrorResponse'
        "409":
          description: |-
            The Entity version specified in this message is lower than
            a previously-received notification, or identical to a previously-received
            notification and the Entity is different.
          content:
            application/json:
              schema:
                $ref: '../shared-components/schemas.yaml#/components/schemas/ErrorResponse'
        "429":
          description: The client issued too many requests in a short period of time.
          content:
            application/json:
              schema:
                $ref: '../shared-components/schemas.yaml#/components/schemas/ErrorResponse'
      security:
      - Authority:
        - utm.availability_arbitration
  /oim/v1/imbalance:
    summary: Submit details about a detected resource demand capacity imbalance
      to the OIM which manages the operation. 
    post:
      tags:
      - Imbalance monitoring 
      summary: Notify an OIM of a demand capacity balance which for which their operation 
        is contributing. 
      description: Notify an OIM of a demand capacity balance which for which their operation 
        is contributing. 
      operationId: notifyDCBImbalanceParticipant
      requestBody:
        content:
          application/json:
            schema:
              $ref: '../DCB/astm-uam-psu-dcb-0.0.0.yaml#/components/schemas/ImbalanceResponse'
        required: true
      responses:
        "204":
          description: DCB imbalance information received successfully.
        "400":
          description: |-
            * One or more parameters were missing or invalid.
            * The Entity could not be parsed, or contains illegal data.
          content:
            application/json:
              schema:
                $ref: '../shared-components/schemas.yaml#/components/schemas/ErrorResponse'
        "401":
          description: "Bearer access token was not provided in Authorization header, token could not be decoded, or token was invalid."
          content:
            application/json:
              schema:
                $ref: '../shared-components/schemas.yaml#/components/schemas/ErrorResponse'
        "403":
          description: |-
            * The access token was decoded successfully but did not include a scope appropriate to this endpoint.
            * The client identified in the access token is not the manager of this Entity according to the receiving client's records.
          content:
            application/json:
              schema:
                $ref: '../shared-components/schemas.yaml#/components/schemas/ErrorResponse'
        "409":
          description: |-
            The Entity version specified in this message is lower than
            a previously-received notification, or identical to a previously-received
            notification and the Entity is different.
          content:
            application/json:
              schema:
                $ref: '../shared-components/schemas.yaml#/components/schemas/ErrorResponse'
        "429":
          description: The client issued too many requests in a short period of time.
          content:
            application/json:
              schema:
                $ref: '../shared-components/schemas.yaml#/components/schemas/ErrorResponse'
      security:
      - Authority:
        - utm.strategic_coordination
  /oim/v1/extent_update:
    summary: Submit updated resource extents and trajectory back to OIM from DCB. This endpoint
      will be called in the case where a new resource is created or the physical definition
      of a resource is updating causing a flight's shared resource extents and trajectory to 
      be out of date.  This endpoint returns the same data as an imbalance intent request 
      on the DCB.  It indicates if the flight is DCB compliant or not (after the change), 
      provides details about imbalances, and also provides the updated resource extents and
      supplemental trajectory for updates to the DSS and other OIMs. 
    post:
      tags:
      - Imbalance monitoring 
      summary: Notify an OIM that the resource interaction of their existing operational intent
        is out of date and must be updated. 
      description: Notify an OIM that the resource interaction of their existing operational intent
        is out of date and must be updated. 
      operationId: notifyExtentsRequireUpdate
      requestBody:
        content:
          application/json:
            schema:
              $ref: '../DCB/astm-uam-psu-dcb-0.0.0.yaml#/components/schemas/ExtentUpdateRequest'
        required: true
      responses:
        "204":
          description: Extent update information received successfully.
        "400":
          description: |-
            * One or more parameters were missing or invalid.
            * The Entity could not be parsed, or contains illegal data.
          content:
            application/json:
              schema:
                $ref: '../shared-components/schemas.yaml#/components/schemas/ErrorResponse'
        "401":
          description: "Bearer access token was not provided in Authorization header, token could not be decoded, or token was invalid."
          content:
            application/json:
              schema:
                $ref: '../shared-components/schemas.yaml#/components/schemas/ErrorResponse'
        "403":
          description: |-
            * The access token was decoded successfully but did not include a scope appropriate to this endpoint.
            * The client identified in the access token is not the manager of this Entity according to the receiving client's records.
          content:
            application/json:
              schema:
                $ref: '../shared-components/schemas.yaml#/components/schemas/ErrorResponse'
        "409":
          description: |-
            The Entity version specified in this message is lower than
            a previously-received notification, or identical to a previously-received
            notification and the Entity is different.
          content:
            application/json:
              schema:
                $ref: '../shared-components/schemas.yaml#/components/schemas/ErrorResponse'
        "429":
          description: The client issued too many requests in a short period of time.
          content:
            application/json:
              schema:
                $ref: '../shared-components/schemas.yaml#/components/schemas/ErrorResponse'
      security:
      - Authority:
        - utm.strategic_coordination

components:
  securitySchemes:
    $ref: '../shared-components/schemas.yaml#/components/securitySchemes'

  schemas:
    GetOperationalIntentDetailsResponse:
      required:
      - operational_intent
      type: object
      properties:
        operational_intent:
          $ref: '../shared-components/schemas.yaml#/components/schemas/OperationalIntent'
      description: Response to peer request for the details of operational intent with the given ID.
    GetOperationalIntentTelemetryResponse:
      required:
      - operational_intent_id
      - telemetry
      type: object
      properties:
        operational_intent_id:
          description: ID of the operational intent which the vehicle reporting telemetry is flying.
          $ref: '../shared-components/schemas.yaml#/components/schemas/EntityID'
        telemetry:
          $ref: '../DSS/astm-uam-psu-dss-0.0.0.yaml#/components/schemas/VehicleTelemetry'
        next_telemetry_opportunity:
          description: |-
            The next telemetry similar to this telemetry is not expected to be
            available until at or after this time, so the polling PSU should
            generally not poll the endpoint providing this response data again
            until at or after that time.  If this field is omitted, then there
            is no current expectation of new telemetry becoming available.
          $ref: '../shared-components/schemas.yaml#/components/schemas/Time'
      description: Response to a peer request for telemetry of an operational intent.
    PutUssAvailabilityDetails:
      required:
      - uss_availability_status
      - subscriptions
      type: object
      properties:
        uss_availability_status:
          description: ID of operational intent that has changed.
          $ref: '../DSS/astm-uam-psu-dss-0.0.0.yaml#/components/schemas/UssAvailabilityStatus'
        subscriptions:
          minItems: 1
          type: array
          description: Subscription(s) prompting this notification.
          items:
            $ref: '../shared-components/schemas.yaml#/components/schemas/SubscriptionState'
      description: |-
        Updated uss availability details. 
    PutConformanceAlert:
      description: |-
        Parameters for an alert about an operation from the CM role. 
      required:
      - alert
      type: object
      properties:
        alert:
          type: string
          description: |-
            Alert about an operation from the CM role.
            'Takeoff': Tracking information has been received indicating that the aircraft has taken off
            'Nonconforming': Tracking information has been received indicating that the aircraft is no longer in conformance with its coordinated (activated or DCB-Noncompliant) operational intent
            'Reconforming': Tracking information has been received indicating that the aircraft is in conformance with its coordinated (activated or DCB-Noncompliant) operational intent after being nonconforming. 
              Reconformance may be because the operation has regained conformance with its previously coordinated operational intent or because the intent has been updated.
          enum:
          - Takeoff
          - Nonconforming
          - Reconforming
      